### ISSUE TITLE
GSEA() qvalue error when using very few terms

### ISSUE THREAD

**Issue by Runsheng** [GuangchuangYu/DOSE#10]
Dear Guangchuang,

I encountered a qvalue error when applying GSEA analysis against only 4 self-built GO terms. 
I tried to reproduce the same error using the test data and code you gave in`http://guangchuangyu.github.io/2015/05/use-clusterprofiler-as-an-universal-enrichment-analysis-tool/`.

The code is
```R
library(DOSE)
library(clusterProfiler)

data(geneList)
gda <- read.delim("all_gene_disease_associations.txt")

disease2gene=gda[, c("diseaseId", "geneId")]
disease2gene_short<-subset(disease2gene, diseaseId %in% c("umls:C0011581","umls:C0024530","umls:C0243026"))
y = GSEA(geneList, TERM2GENE=disease2gene_short)
```
And the error message is
```
Error in pi0est(p, ...) : 
ERROR: The estimated pi0 <= 0. Check that you have valid p-values or use a different range of lambda.
```
I tried this code in both ubuntu14.04 and windows 7 with R version 3.2.4 (DOSE package from bioconductor or from github).

I only need a GSEA "runningScore" plot, so I simply deleted the using of pi0est() and force qvalues to be "NA" in function GSEA_internal(). This is a dirty fix and I wonder if you can check why this happened. 

Best regards,
Runsheng Li

**Comment by GuangchuangYu** [comment]
This is expected. qvalue need a whole pvalue distribution to estimate.

I just update the source code to prevent throw error if qvalues were failed to estimate.
