### ISSUE TITLE
Question: How to combine multiple enrichmentResult objects

### ISSUE THREAD

**Issue by wyu** [GuangchuangYu/DOSE#12]
Hi, is there a way to combine the results from multiple enrichment runs to generate a single "cnetplot"? It'd be even better if we can render the network plots in D3Network or other interactive viewer.

By the way, your packages are tremendously useful for us. We are using them as the core of our interactive Shiny app. Big thanks to you for your contribution and kindness.

Wen

**Comment by GuangchuangYu** [comment]
What do you mean by **combining** them?

**Comment by wyu** [comment]
Hi, I'm using the universal gene enricher that can be called for different gene sets. Each call will generate an instance of enrichResult object (ego). A call to 'cnetplot' will generate a nice plot for each instance of 'ego'. 

Supposedly I can invoke it on GO, KEGG and MSigDB:C5 and got three instances of 'ego' from each calls. Is it possible to combine all three of them into one so I can generate a 'cnetplot' that contains the merged networks. 
 
On the cnetplot output, I'm wonder if there is a way to construct an igraph object for the network, such that I can pass it to a htmlwidget like d3network to render it into an interactive force-layout graph.

Thanks!
Wen

ego= enricher(gene=geneids, universe=background, TERM2GENE=gset, TERM2NAME=nset, pvalueCutoff=pv, qvalueCutoff=qv, pAdjustMethod=adj);   

cnetplot(ego, categorySize="pvalue", foldChange=geneList)

**Comment by GuangchuangYu** [comment]
In github version of `DOSE`, you can do something like this:

```r
library(DOSE)
data(geneList)
x=enrichDO(names(geneList)[1:100])
y=cnetplot(x)
yy=igraph_to_networkD3(y)
forceNetwork(Links=yy$links, Nodes=yy$nodes, Source='source', Target='target', NodeID='name', Group='name')
```

I am not familiar with networkD3, you can fork `DOSE` and change the cnetplot function to output igraph object to meet your need of networkD3 visualization.

**Comment by kenmcgarry** [comment]
Hi Guangchuang,

How do I get a list of DO terms assigned to a disease using DOSE please? So for Alzheimer's (DOID:10652) how can I access them?

Thanks

Ken

**Comment by GuangchuangYu** [comment]
@kenmcgarry For user question, please post to biostar. Thanks.
