### ISSUE TITLE
Some functions documented are not exported

### ISSUE THREAD

**Issue by llrs** [GuangchuangYu/DOSE#21]
I was trying to understand which are the differences between the DOSE::clusterSim and the GOSemSim::clusterSim, and I noticed a couple of things. 
The examples of clusterSim in DOSE don't work (maybe that's why it is commented)  but do if you change to:
```r
cluster1 <- c("835", "5261","241", "994")
cluster2 <- c("307", "308", "317", "321", "506", "540", "378", "388", "396")
DOSE::clusterSim(cluster1, cluster2)
```
The example of GOSemSim didn't work neither, you need to update the semData was renamed to godata (this happen in many  examples of GOSemSim!)
```r
d <- godata('org.Hs.eg.db', ont="MF")
cluster1 <- c("835", "5261","241", "994")
cluster2 <- c("307", "308", "317", "321", "506", "540", "378", "388", "396")
GOSemSIM::clusterSim(cluster1, cluster2, semData=d, measure="Wang")
```
I am interested in the computeIC, gene2DO functions of DOSE, which are documented but they are not exported, could you expand the documentation (computeIC doesn't have a Return section) and export them?

Many thanks

**Comment by GuangchuangYu** [comment]
1. the source code you posted here are all work.
2. doc and code are consistent and the parameter is `semData` not `godata`.
3. `computeIC` is not exported since it was used internally.

**Comment by llrs** [comment]
1. The code I posted works but the DOSE `example(clusterSim)` and GOSemSim `example(clusterSim)` don't (even after removing the `##` ), I suggest the code above to make the examples work. 
2. If you remove the comments of the examples you could check that the examples are consistent with the code. The parameter `semData` is for the GOSemSim function but the function that create the ojbect is `godata` in the example it uses `semData` as the[ name of the function](https://github.com/GuangchuangYu/GOSemSim/blob/a79dc9668fa8fd744eb0d885094759d583c5fbb2/R/clusterSim.R#L29). 
3. Well I thought it would be useful for other package to be able to build upon your `computeIC`, but as you wish. 
 Is gene2DO exported? [The lines](https://github.com/GuangchuangYu/DOSE/blob/712d3ca63097a7ddcaa7f85e80a01a30d850ab58/R/utilities.R#L97-L106) 97 -105 which are the roxygen2 notes don't have a `#' @export ` line.

**Comment by GuangchuangYu** [comment]
thanks for your feedback. 1 and 2 were all fixed.

For 3, now `gene2DO` is exported.
