### ISSUE TITLE
improve GO and DO enrichment for GTEx papers?

### ISSUE THREAD

**Issue by dalloliogm** [GuangchuangYu/DOSE#6]
Hi,
this is not a issue report, but rather an analysis that could be done.

The ENCODE consortium has recently published a great paper on Gene Expression from the GTEx dataset. The data made available is great, however a criticism raised on pubpeer is that the gene ontology enrichment analysis was done with DAVID, a tool that has not been updated in the last five years: https://pubpeer.com/publications/EB99BD086B27075CFF5278F1CEAA57

Would it be interesting to reproduce the Gene Ontology analysis presented in the paper using DOSE/clusterCompare, to see if the results change? It would be good publicity for the library.

**Comment by GuangchuangYu** [comment]
Thanks for your information. That's a good idea. Let's reproduce the GO/DO analyses.

**Comment by GuangchuangYu** [comment]
I just compare BP ontology, clusterProfiler have more genes annotated and found more terms enriched. The result from clusterProfiler is definitely a superset of david, see https://github.com/GuangchuangYu/enrichment4GTEx_clusterProfiler.

**Comment by dalloliogm** [comment]
Wow, this is wonderful, congratulations!
It seems that the results are quite comparable, which is good, because it means that DAVID and clusterProfiler are comparable.

What is the best way to publicize this work? I can add a comment to the pubpeer discussion, and I can twit it.

**Comment by GuangchuangYu** [comment]
I see you already twit it. Thanks! I will compare KEGG either and add DO enrichment.

After the comparison, I will also perform GSEA to see whether something new can be found.
